import Head from 'next/head'
import React from 'react';
import styles from '../styles/Home.module.css'
import SpeakingSection from '../sections/SpeakingSection';
import ResultsSection from '../sections/ResultsSection';
import QuestionSection from '../sections/QuestionSection';
import StoreProvider from '../utils/store';

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>English Speaking App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <StoreProvider>
        <ResultsSection />
        <QuestionSection />
        <SpeakingSection />
      </StoreProvider>
      </main>
    </div>
  )
}
